db.url=jdbc:mysql://127.0.0.1:3306/database_name
db.username=username
db.password=password
db.driverClassName=com.mysql.cj.jdbc.Driver

#this is template file , if you want to use, create file db.properties and push this code to it