
# Cau hinh H2 Database
spring.datasource.url=
spring.datasource.driverClassName=
spring.datasource.username=
spring.datasource.password=
spring.jpa.database-platform=
spring.jpa.hibernate.ddl-auto=
spring.jpa.show-sql=
spring.h2.console.enabled=
spring.h2.console.path=