name=nghiaduong

spring.datasource.driver=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://172.26.177.28:3306/AttendanceManagement
spring.datasource.username=javauser
spring.datasource.password=yourpassword

